[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,generatorId=`com.igormaznitsa:idea-mindmap:intellij-2024.17.0-WebStorm`
---

# layout\.tsx

## metadata: <br/>Metadata
> align=`left`


### normalizeCMSPageMeta\(<br/>getCmsPageMetaDefault\(\),<br/>metaHandlers<br/>\)
> align=`left`,mmd.emoticon=`application`

- NOTE
<pre>Создает MetaData для страницы
из данных TCmsPageMeta</pre>

#### getCmsPageMetaDefault\(\)
> align=`left`,fillColor=`#00FF12`,mmd.emoticon=`application`


##### mainPageMeta
> align=`left`,fillColor=`#808080`,mmd.emoticon=`barcode`

- NOTE
<pre>cmsPageDataList[0]?.attributes.meta || {}</pre>

##### cmsPageMetaDefault
> fillColor=`#808080`,mmd.emoticon=`barcode`

- NOTE
<pre>TCmsPageMeta default</pre>

#### metaHandlers
> align=`left`,fillColor=`#00FF12`

- NOTE
<pre>Обработчики noIndex, noFollow, canonical,
alternate, og, twitter</pre>

## RootLayout
> align=`left`,fillColor=`#FF00FF`


### Header
> align=`left`,fillColor=`#FF00FF`


#### hrefMailTo, <br/>email, <br/>\.\.\.rest
> align=`left`,fillColor=`#808080`

- NOTE
<pre>returns Promise&lt;IContactsHeaderData&gt;

export interface IContactsHeaderData {
  hrefMailTo: string;
  hrefTelTo: string;
  telLabel: string;
  telAriaLabel: string;
  email: string;
  addressItems: string[];
}</pre>

##### getContactsHeaderData\(\)
> fillColor=`#00FF12`,mmd.emoticon=`application`

- NOTE
<pre>MOCK CMS GETTERS to be replaced with real getters on fetching CMS Data
it is temporary used for async getting data from mock cms...
It returns Promise&lt;IContactsHeaderData | null&gt;</pre>

###### cmsHeaderData\.contactsData
> fillColor=`#808080`,mmd.emoticon=`barcode`

- NOTE
<pre>export interface ICmsHeaderData {
  logoData?: {
    linkHref: string;
    imageData: TImageProps;
  };
  contactsData?: IContactsHeaderData;
}



const contactsData?: IContactsHeaderData = {
  hrefMailTo: &quot;mailto:agl@ag-landscape.com&quot;,
  hrefTelTo: &quot;tel:+13034679619&quot;,
  telLabel: &quot;303-467-9619&quot;,
  telAriaLabel: &quot;make a call to the master&quot;,
  email: &quot;agl@ag-landscape.com&quot;,
  addressItems: [&quot;4310 Youngfield St.&quot;, &quot;Wheat Ridge, CO&quot;],
};
</pre>

#### wrapperProps, <br/>imageProps
> align=`left`,fillColor=`#808080`

- NOTE
<pre>The data, taken from the mock cms for building logo block in header...

export type TNavImageWrapperProps = {
  wrapperProps: TWrapperProps&lt;INavLinkProps&gt;; //href is required...
  imageProps: TImageProps;
};

export type TWrapperProps&lt;P&gt; = Omit&lt;P, &quot;style&quot;&gt; &amp; {
  style?: React.CSSProperties;
  [key: `data-${string}`]: string | undefined;
};

export interface INavLinkProps extends React.ComponentProps&lt;typeof Link&gt; {
  href: string;
  exact?: boolean; // exact path match or &quot;starts from ...&quot;
  className?: string;
  replace?: boolean;
  activeClassName?: string; //is used when &quot;active&quot;
}

// Final shape of image data (used in CMS, UI configs, etc.)
export type TImageProps = {
  src: TImageSource;
  alt: string;

  // Required width for container, aspect ratio will be calculated
  width: number;

  // Optional height — required if src is a string (not StaticImageData)
  height?: number;

  //objectFit?: React.CSSProperties['objectFit'];
  objectFit?: string; //objectFit is taken from imageProps.objectFit which is string

  // Responsive sizes
  breakPoints?: TImageSizes;

  // Allow passing any other native &lt;img&gt; or &lt;Image&gt; props if needed
  [key: string]: unknown;
};
</pre>

##### getLogoBlockImageData\(\)
> fillColor=`#00FF00`,mmd.emoticon=`application`

- NOTE
<pre>MOCK CMS GETTERS to be replaced with real getters on fetching CMS Data
it is temporary used for async getting data from mock cms...
It returns Promise&lt;TNavImageWrapperProps | null&gt;
</pre>

###### cmsHeaderData\.logoData
> fillColor=`#808080`,mmd.emoticon=`barcode`

- NOTE
<pre>export interface ICmsHeaderData {
  logoData?: {
    linkHref: string;
    imageData: TImageProps;
  };
  contactsData?: IContactsHeaderData;
}

// Final shape of image data (used in CMS, UI configs, etc.)
export type TImageProps = {
  src: TImageSource;
  alt: string;

  // Required width for container, aspect ratio will be calculated
  width: number;

  // Optional height — required if src is a string (not StaticImageData)
  height?: number;

  //objectFit?: React.CSSProperties['objectFit'];
  objectFit?: string; //objectFit is taken from imageProps.objectFit which is string

  // Responsive sizes
  breakPoints?: TImageSizes;

  // Allow passing any other native &lt;img&gt; or &lt;Image&gt; props if needed
  [key: string]: unknown;
};</pre>

###### buildLogoBlockImageData\(logData\)
> fillColor=`#00FF12`,mmd.emoticon=`application`

- NOTE
<pre>It is used to handle the received CMS header data, or mock cms data
It returns TNavImageWrapperProps | null
</pre>

#### navLinksData
> fillColor=`#808080`

- NOTE
<pre>export type THeaderNavMenuItem = {
  id: string;
  label: string;
  href: string | null;
  parentId: string | null;
  order: number;
};

export type THeaderNavMenuNode = THeaderNavMenuItem &amp; {
  children?: THeaderNavMenuNode[];
};

navLinksData: THeaderNavMenuNode[]</pre>

##### getHeaderNavMenuTree\(\)
> fillColor=`#00FF12`,mmd.emoticon=`application`

- NOTE
<pre>MOCK CMS GETTERS to be replaced with real getters on fetching CMS Data
it is temporary used for async getting data from mock cms...

It returns Promise&lt;THeaderNavMenuNode[] | null&gt;</pre>

###### cmsHeaderData\.navMenuData
> fillColor=`#808080`,mmd.emoticon=`barcode`

- NOTE
<pre>THeaderNavMenuItem[]

export type THeaderNavMenuItem = {
  id: string;
  label: string;
  href: string | null;
  parentId: string | null;
  order: number;
};

</pre>

###### buildHeaderNavMenuTree\(navMenuData\)
> fillColor=`#00FF12`,mmd.emoticon=`application`

- NOTE
<pre>Builds a hierarchical navigation tree from a flat list of menu items.

Returns THeaderNavMenuNode[]

</pre>

#### \<LogoBlock<br/> wrapperProps=\{wrapperProps\}<br/> imageProps=\{imageProps\}<br/> textLinkHref=\{hrefMailTo\}<br/>\>
> align=`left`,fillColor=`#FF00FF`

- NOTE
<pre>function LogoBlock({
  wrapperProps,
  imageProps,
  textLinkHref,
  children,
}: TLogoBlockProps)</pre>

##### \<ImageWrapper\<INavLinkProps\><br/> wrapper=\{NavLink\}<br/> wrapperProps=\{wrapperPropsStyled\}<br/> imageProps=\{imageProps\}<br/>/\>
> align=`left`,fillColor=`#FF00FF`

- NOTE
<pre>wraps logo image</pre>

##### \<IconTextLink<br/> href=\{textLinkHref\}<br/> aria\-label="mail to us"<br/> tabIndex=\{0\}<br/> className="iconTextLink"<br/>\>
> align=`left`,fillColor=`#FF00FF`


#### \<ContactsWrapper <br/>  data=\{rest\} <br/>/\>
> align=`left`,fillColor=`#FF00FF`


#### \<NavWrapper <br/>  data=\{navLinksData\} <br/>/\>
> align=`left`,fillColor=`#FF00FF`


### children
> align=`left`,fillColor=`#241919`,textColor=`#FFFFFF`


## App
> fillColor=`#FFC800`,leftSide=`true`,textColor=`#0000FF`

