import { promises as fs } from "fs";
import * as path from "path";
import { toPathUrl, getMediaEntries, getUniqueMediaEntries, generateTSModule, getDescriptors } from "./utils";

/* =========================================================
 * Auto-generates src/lib/generated/videosMap.ts
 * 1. Fetches video lists from CMS or local mocks
 * 2. Downloads remote files into videos/ (alias @v/*)
 * 3. Deduplicates by basename
 * 4. Writes static imports for next-video optimisation
 * ----------------------------------------------------------
 *! include to scripts:
 * "generate:videos": "tsx scripts/processVideos.ts",
 *
 *! include to dev:
 * "npm-run-all -s tidy generate:images generate:videos && concurrently \"next dev --turbopack\" \"npx next-video sync --watch\"",
 *
 *! include to build:
 * "npm-run-all -s tidy generate:images generate:videos npx next-video sync next build"
 *
 * TODO: read docs/video-strategy.md
 *
 * ========================================================= */

/* =========================================================
*  Configuration
* TODO: To make docs/video-strategy.md
* ========================================================= */
const SOURCE_DIR = toPathUrl("videos");
const mediaMapFile = "videosMap.ts";
const OUT_FILE   = toPathUrl(`src/lib/generated/${mediaMapFile}`);

const SOURCES: string[] = [
	//"https://cms.example.com/api/videos",
	"scripts/lib/mockVideos.ts",  // export default mock videos: ICmsVideoItem[] from scripts
];

/* ------------------------------------------------------------------ */
/*  Main                                                              */
/* ------------------------------------------------------------------ */
(async () => {
	console.log("📥  Fetching media list…");

	/* ensure folder exists */
	await fs.mkdir(SOURCE_DIR, { recursive: true });

	const items = await getMediaEntries(SOURCES);

	/* ---------- dedupe by basename ---------- */
	const unique = getUniqueMediaEntries(items);

	/* ---------- progress bar ---------- */
	const bar = new cliProgress.SingleBar({}, cliProgress.Presets.shades_classic);
	bar.start(unique.length, 0);

	const descriptors: {
		varName: string;
		baseName: string;
		importPath: string;
	}[] = [];

	for (const [idx, it] of unique.entries()) {
		bar.update(idx + 1);

		const isRemote = it.url.startsWith('http');
		const baseName = path.basename(it.url);
		const fileName = isRemote ? `${AUTO_PREFIX}${baseName}` : baseName;
		const localPath = path.join(VIDEOS_DIR, fileName);

		const exists = await fs.stat(localPath).catch(() => false);

		if (!exists) {
			/* downloading remote file if not found in localPath */
			if (isRemote) {
				await download(it.url, localPath);
				console.log(`⬇️  Downloaded: ${it.url} → ${fileName}`);
			}
			else {
				console.error(`\n❌ [processVideos]: local file ${baseName} is not found at ${localPath}`);
				process.exit(1);
			}
		}

		/* build descriptor */
		const varName = `item_${idx}`;
		const importPath = `@v/${fileName}`;
		descriptors.push({ varName, baseName, importPath });
	}

	bar.stop();

	/* ---------- generate TS module ---------- */
	const imports = descriptors.map(d => `import ${d.varName} from "${d.importPath}";`);
	const mapEntries = descriptors.map(d => `  "${d.baseName}": ${d.varName},`);

	const code = [
		'/**',
		' * ⚠️ AUTO-GENERATED FILE – DO NOT EDIT MANUALLY',
		' * Generated by:  npm run generate:videos',
		' */',
		'',
		...imports,
		'',
		'export const videoMap = {',
		...mapEntries,
		'} as const;',
		'',
		'export type VideoMapKey = keyof typeof videoMap;',
		'',
	].join('\n');

	await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
	await fs.writeFile(OUT_FILE, code, 'utf8');

	console.log('✅  videosMap.ts created / updated');
})().catch(err => {
	console.error('❌  Error:', err);
	process.exitCode = 1;
});